/* SPDX-License-Identifier: MIT */

#ifndef GRAPHION_TESTS_GION_TEST_PARSER_CASES_H
#define GRAPHION_TESTS_GION_TEST_PARSER_CASES_H

#define GRAPHION_PARSER_TEST_CASES(X)                  \
  X(parser_decode_valid_program)                       \
  X(parser_rejects_truncated_input)                    \
  X(frontend_parse_and_ir_lowering)                    \
  X(frontend_rejects_invalid_source)                   \
  X(frontend_source_to_vm_execution)                   \
  X(frontend_reference_graph_execution_examples)       \
  X(gion_source_path_detection)                        \
  X(gion_scalar_assignments_and_prints)                \
  X(gion_scalar_feature_varied_names)                  \
  X(gion_unknown_variable_errors)                      \
  X(gion_partial_execution_stops_at_first_unsupported_line) \
  X(gion_reserved_name_errors)                         \
  X(gion_assignment_syntax_errors)                     \
  X(gion_arithmetic_expressions)                       \
  X(gion_string_concatenation)                         \
  X(gion_print_string_coercion)                        \
  X(gion_compound_assignments)                         \
  X(gion_compound_assignment_errors)                   \
  X(gion_arithmetic_precedence_and_associativity)      \
  X(gion_arithmetic_runtime_errors)                    \
  X(gion_arithmetic_syntax_errors)                     \
  X(gion_mixed_scalar_values)                          \
  X(gion_capacity_errors)                              \
  X(gion_bits_literals)                                \
  X(gion_bits_literal_syntax_errors)                   \
  X(gion_bits_equality)                                \
  X(gion_bits_inequality)                              \
  X(gion_bits_mixed_type_errors)                       \
  X(gion_bits_and)                                     \
  X(gion_bits_and_runtime_errors)                      \
  X(gion_bits_or)                                      \
  X(gion_bits_or_runtime_errors)                       \
  X(gion_bits_xor)                                     \
  X(gion_bits_xor_runtime_errors)                      \
  X(gion_bits_not)                                     \
  X(gion_bits_not_runtime_errors)                      \
  X(gion_bits_shl)                                     \
  X(gion_bits_shl_runtime_errors)                      \
  X(gion_bits_shr)                                     \
  X(gion_bits_shr_runtime_errors)                      \
  X(gion_list_literals_and_prints)                     \
  X(gion_list_runtime_errors)                          \
  X(gion_list_syntax_errors)                           \
  X(gion_dict_literals_and_prints)                     \
  X(gion_dict_runtime_errors)                          \
  X(gion_dict_syntax_errors)                           \
  X(gion_tuple_literals_and_prints)                    \
  X(gion_tuple_runtime_errors)                         \
  X(gion_tuple_syntax_errors)                          \
  X(gion_set_literals_and_prints)                      \
  X(gion_set_runtime_errors)                           \
  X(gion_set_syntax_errors)                            \
  X(gion_struct_declarations_and_instances)            \
  X(gion_struct_runtime_errors)                        \
  X(gion_struct_syntax_errors)                         \
  X(gion_empty_graph_declaration)                      \
  X(gion_empty_hypergraph_declaration)                 \
  X(gion_hypergraph_vertex_block_declaration)          \
  X(gion_hypergraph_vertex_attributes)                 \
  X(gion_hypergraph_hyperedge_declaration)             \
  X(gion_hypergraph_vertex_and_hyperedge_attributes)   \
  X(gion_hypergraph_membership_query_builtins)         \
  X(gion_hypergraph_listing_query_builtins)            \
  X(gion_hypergraph_structure_mutation_statements)     \
  X(gion_hypergraph_attribute_mutation_statements)     \
  X(gion_hypergraph_removal_mutation_statements)       \
  X(gion_hypergraph_error_coverage)                    \
  X(gion_graph_node_block_declaration)                 \
  X(gion_graph_explicit_ids_have_priority)             \
  X(gion_graph_node_attributes)                        \
  X(gion_graph_node_attribute_defaults)                \
  X(gion_graph_undirected_edge_declaration)            \
  X(gion_graph_edge_attributes)                        \
  X(gion_graph_directed_edge_declaration)              \
  X(gion_graph_inspection_builtins)                    \
  X(gion_graph_attribute_lookup_builtins)              \
  X(gion_graph_membership_query_builtins)              \
  X(gion_graph_listing_query_builtins)                 \
  X(gion_graph_structure_mutation_statements)          \
  X(gion_graph_attribute_mutation_statements)          \
  X(gion_graph_removal_mutation_statements)            \
  X(gion_graph_mutation_error_coverage)                \
  X(gion_graph_numeric_id_gap_warnings)                \
  X(gion_graph_declaration_syntax_errors)              \
  X(gion_graph_declaration_column_diagnostics)         \
  X(gion_print_syntax_errors)                          \
  X(gion_unterminated_string_errors)                   \
  X(gion_invalid_identifier_errors)                    \
  X(gion_trailing_token_errors)                        \
  X(gion_reference_before_definition_errors)           \
  X(gion_unknown_identifier_column_diagnostics)         \
  X(gion_delimiter_column_diagnostics)                  \
  X(gion_reassignment_and_type_change)                 \
  X(gion_copy_chains_and_blank_lines)                  \
  X(gion_late_line_error_diagnostics)                  \
  X(gion_unexpected_indentation_errors)                \
  X(gion_comments)                                     \
  X(gion_comment_errors)                               \
  X(gion_unmapped_vm_error_diagnostics)                \
  X(gion_warning_comments_are_ignored)                 \
  X(gion_warning_comments_are_ignored_from_path)       \
  X(gion_if_elif_else_control_flow)                    \
  X(gion_if_elif_else_errors)                          \
  X(gion_control_header_column_diagnostics)            \
  X(gion_match_control_flow)                           \
  X(gion_match_errors)                                 \
  X(gion_ternary_expressions)                          \
  X(gion_ternary_runtime_errors)                       \
  X(gion_ternary_syntax_errors)                        \
  X(gion_boolean_short_circuit)                        \
  X(gion_boolean_short_circuit_runtime_errors)         \
  X(gion_equality_expressions)                         \
  X(gion_equality_runtime_errors)                      \
  X(gion_equality_syntax_errors)                       \
  X(gion_inequality_expressions)                       \
  X(gion_inequality_runtime_errors)                    \
  X(gion_inequality_syntax_errors)                     \
  X(gion_less_than_expressions)                        \
  X(gion_less_than_runtime_errors)                     \
  X(gion_less_than_syntax_errors)                      \
  X(gion_less_equal_expressions)                       \
  X(gion_less_equal_runtime_errors)                    \
  X(gion_less_equal_syntax_errors)                     \
  X(gion_greater_than_expressions)                     \
  X(gion_greater_than_runtime_errors)                  \
  X(gion_greater_than_syntax_errors)                   \
  X(gion_greater_equal_expressions)                    \
  X(gion_greater_equal_runtime_errors)                 \
  X(gion_greater_equal_syntax_errors)                  \
  X(gion_and_expressions)                              \
  X(gion_and_runtime_errors)                           \
  X(gion_and_syntax_errors)                            \
  X(gion_or_expressions)                               \
  X(gion_or_runtime_errors)                            \
  X(gion_or_syntax_errors)                             \
  X(gion_not_expressions)                              \
  X(gion_not_runtime_errors)                           \
  X(gion_not_syntax_errors)                            \
  X(gion_nand_expressions)                             \
  X(gion_nand_runtime_errors)                          \
  X(gion_nand_syntax_errors)                           \
  X(gion_nor_expressions)                              \
  X(gion_nor_runtime_errors)                           \
  X(gion_nor_syntax_errors)

#define GRAPHION_DECLARE_TEST(name) int test_##name(void);
GRAPHION_PARSER_TEST_CASES(GRAPHION_DECLARE_TEST)
#undef GRAPHION_DECLARE_TEST

#endif
