from __future__ import annotations

import pathlib


RESULTS_ROOT = pathlib.Path("benchmarks/results")

ASM_RESULTS_DIR = RESULTS_ROOT / "asm"
CROSS_COMPILER_RESULTS_DIR = RESULTS_ROOT / "cross-compiler"
OPTIMIZATION_RESULTS_DIR = RESULTS_ROOT / "optimization"
PERFORMANCE_RESULTS_DIR = RESULTS_ROOT / "performance"
RELEASE_RESULTS_DIR = RESULTS_ROOT / "release"
SMOKE_RESULTS_DIR = RESULTS_ROOT / "smoke"

PERFORMANCE_REPORTS_DIR = pathlib.Path("docs/performance/reports")

ASM_FALLBACK_JSON = ASM_RESULTS_DIR / "asm_fallback_report_latest.json"
ASM_HARDENING_PARITY_JSON = ASM_RESULTS_DIR / "asm_hardening_parity_latest.json"
CROSS_COMPILER_REPORT_JSON = CROSS_COMPILER_RESULTS_DIR / "cross_compiler_report_latest.json"
CROSS_COMPILER_WINDOWS_JSON = CROSS_COMPILER_RESULTS_DIR / "cross_compiler_windows_msvc.json"
CROSS_COMPILER_LINUX_GCC_JSON = CROSS_COMPILER_RESULTS_DIR / "cross_compiler_linux_gcc.json"
CROSS_COMPILER_LINUX_CLANG_JSON = CROSS_COMPILER_RESULTS_DIR / "cross_compiler_linux_clang.json"
OPTIMIZATION_REPORT_JSON = OPTIMIZATION_RESULTS_DIR / "optimization_report_latest.json"
OPTIMIZATION_WINDOWS_JSON = OPTIMIZATION_RESULTS_DIR / "optimization_report_windows.json"
OPTIMIZATION_LINUX_JSON = OPTIMIZATION_RESULTS_DIR / "optimization_report_linux.json"
PERFORMANCE_LATEST_JSON = PERFORMANCE_RESULTS_DIR / "latest.json"
PERFORMANCE_WINDOWS_JSON = PERFORMANCE_RESULTS_DIR / "windows_100x_latest.json"
PERFORMANCE_LINUX_JSON = PERFORMANCE_RESULTS_DIR / "linux_100x_latest.json"
PERFORMANCE_RUST_WINDOWS_JSON = PERFORMANCE_RESULTS_DIR / "rust_windows_100x_latest.json"
PERFORMANCE_RUST_LINUX_JSON = PERFORMANCE_RESULTS_DIR / "rust_linux_100x_latest.json"
DISPATCH_WINDOWS_JSON = PERFORMANCE_RESULTS_DIR / "dispatch_variants_windows.json"
DISPATCH_LINUX_JSON = PERFORMANCE_RESULTS_DIR / "dispatch_variants.json"
LINUX_10X_JSON = PERFORMANCE_RESULTS_DIR / "linux_10x.json"
RELEASE_CANDIDATE_PGO_JSON = RELEASE_RESULTS_DIR / "release_candidate_pgo.json"

ASM_FALLBACK_MD = PERFORMANCE_REPORTS_DIR / "ASM_FALLBACK_REPORT.md"
ASM_HARDENING_PARITY_MD = PERFORMANCE_REPORTS_DIR / "ASM_HARDENING_PARITY.md"
CROSS_COMPILER_REPORT_MD = PERFORMANCE_REPORTS_DIR / "CROSS_COMPILER_REPORT.md"
OPTIMIZATION_REPORT_MD = PERFORMANCE_REPORTS_DIR / "OPTIMIZATION_REPORTS.md"
PERFORMANCE_RESULTS_MD = PERFORMANCE_REPORTS_DIR / "PERFORMANCE_RESULTS.md"
